### ISSUE TITLE
Trained model

### ISSUE THREAD

**Issue by ufukefe** [mazenmel/Deep-homography-estimation-Pytorch#2]
Hello, thanks for implementing the model. Is there pre-trained model available? I want to try the model and fine tune if possible. Thank you!

**Comment by xRoms** [comment]
Hi, im interested too!

**Comment by mazenmel** [comment]
HI, sorry for the late response. Unfortunately, I don't have the pre-trained weights file for now, but I will retrain it again and upload the file, I will keep you updated.

**Comment by Mordokkai** [comment]
Hi,
I'm interested too!

**Comment by mazenmel** [comment]
Hi, I have just uploaded the pre-trained model.
To load the it just execute the following:

#define the network class "Model"
model = Model() 
optimizer = optim.SGD(model.parameters(),lr=0.005, momentum=0.9)
checkpoint = torch.load('./DeepHomographyEstimation2.pth')
model.load_state_dict(checkpoint['state_dict'])
optimizer.load_state_dict(checkpoint['optimizer'])
epoch = checkpoint['epoch']
model.eval()

**Comment by Mordokkai** [comment]
Thx a lot!

**Comment by ufukefe** [comment]
Thank you! :)
