### ISSUE TITLE
How do we go from H4point to actual homography matrix ?

### ISSUE THREAD

**Issue by rajesh-bhat** [mazenmel/Deep-homography-estimation-Pytorch#7]

**Comment by mazenmel** [comment]
Hi,
You can use getPerspectiveTransform() of opncv.

**Comment by rajesh-bhat** [comment]
@mazenmel  ... What would be the source points and destination points in getPerspectiveTransform() in this scenario?

**Comment by A-Kerim** [comment]
Maybe you can try the following: 

    patch_size = 128
    top_point = (32, 32)
    left_point = (patch_size + 32, 32)
    bottom_point = (patch_size + 32, patch_size + 32)
    right_point = (32, patch_size + 32)

    four_points = [top_point, left_point, bottom_point, right_point]
        
    M = cv2.getPerspectiveTransform(four_points,four_points+H4p)
