### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by fanzhen12** [mazenmel/Deep-homography-estimation-Pytorch#8]
dear Mazen Mel, hello, I want to ask you one question: how to get the dataset which could be used to train the net. I put some picture(.jpg) in train2017, val2017 and test2017 folders, and after I run DataGenerationAndProcessing.py, there are three folders appeared, and in each folder, there is one file in it(.npy), and the I run trainandvalidation.py, something goes wrong
![image](https://user-images.githubusercontent.com/40566781/145352089-656eabeb-3b0a-4ce7-8452-88ee90c1323d.png)
![image](https://user-images.githubusercontent.com/40566781/145352130-54064424-2692-4bbc-bd89-64e31d39e7a9.png)
![image](https://user-images.githubusercontent.com/40566781/145352180-fc0d8f3b-4f3f-4578-9e46-7204881c869e.png)

**Comment by mazenmel** [comment]
Hi, please check the file path, it should be ´data/train2017processed/COCO_test201.npy´ the last forward slash is missing.

**Comment by fanzhen12** [comment]
thank you very much, I have solved it, thank you

**Comment by fanzhen12** [comment]
dear mazenmel, I have a question, I can't solve it by myself: 
![image](https://user-images.githubusercontent.com/40566781/149610353-f8592809-db04-4273-8b0f-d5f04ea5a5d8.png)
when I run DeepHomographyEstimation.py, this error appeared, and the line is:
![image](https://user-images.githubusercontent.com/40566781/149610382-fe68ac08-ce81-4fc7-8560-ec2c4d26ed04.png)
I'd like to ask you why, could you help me.
